### ISSUE TITLE
Url erroné

### ISSUE THREAD

**Issue by LaurentDardenne** [Stephanevg/RegardsCitoyenPS#2]
Salut,
dans le fichier Readme.md, l'url  d'un site est erroné :
www .regardscitoyen**S**.org

**Comment by Stephanevg** [comment]
Merci pour le retour @LaurentDardenne 
Fixed -> https://github.com/Stephanevg/RegardsCitoyenPS/commit/fa8f31bc0c0b7d57cf4e1061e8870bd9b99072bf
